### ISSUE TITLE
Trouble setting up

### ISSUE THREAD

**Issue by thelazyone** [Aloeminium108/lenia#1]
Whle I undestand it might be due to my lack of knowledge, I am finding an issue while trying to serving my own local lenia. 

![image](https://github.com/user-attachments/assets/d4288395-10f8-4043-a140-363d72f86777)

It would be lovely to have a list of prerequisites and steps to be able set it up and running.

The steps I took are:

`npm install react-scripts --save`
`npm run build`
`npm install -g serve`
`serve -s build`

I get a serving link to localhost, but while inspecting the page the error is what's shown in the image above.

**Comment by Aloeminium108** [comment]
I apologize, but I was unable to recreate the error you are getting.

Starting from scratch, the exact setup steps I used were:

`git clone https://github.com/Aloeminium108/lenia`
`cd lenia/react-app/`
`npm install`
`npm start`

**Comment by thelazyone** [comment]
I have no idea why i did the commands that I did, my apologies. It now works.

I would recommend a small paragraph in the readme.md with simply "do this to run", just in case.

**Comment by Aloeminium108** [comment]
I'm just glad it works now! Setup steps have been added to the readme
